mercado_livre_client_id: "mercado_livre_client_id"
mercado_livre_secret: "mercado_livre_secret"
mercado_livre_api_url: "mercado_livre_api_url"
mercado_livre_redirect_url: "mercado_livre_redirect_url"
mercado_livre_execute_times: "6h"


